### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by PabloBona** [PabloBona/space-travelers#25]
[Kanban Board Setup](https://github.com/PabloBona/space-travelers/projects/1)

Our team has three members:
@hajnaloltyan 
@Alibaba2023 
@PabloBona

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/YPI7uEvEZr7siYRlZD/giphy.gif)

# Hi @PabloBona, @hajnaloltyan & @Alibaba2023 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Proper Kanban board template is used ✔
- All tasks are assigned to team members ✔
- All tasks are distributed fairly ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
